### ISSUE TITLE
Optimistic updates lead to weird partial results (`null` nodes)

### ISSUE THREAD

**Issue by lukasluecke** [FormidableLabs/urql-exchange-graphcache#80] opened 2019-09-13 17:40 UTC
Trying to use optimistic updates currently produces weird results for me. I'll try to add a reproduction later, but not sure when I'll get to that 🙈 

Query:
```graphql
query Tree($rootId: ID!) {
    root(id: $rootId) {
        id
        items {
            edges {
                node {
                    id
                    name
                }
            }
        }
    }
}
```

Mutation:
```graphql
mutation UpdateItem($id: ID!, $name: String) {
    updateItem(input: {id: $id, name: $name}) {
        item {
            id
            name
        }
    }
}
```

Optimistic:
```js
updateItem: (variables, cache) => {
    const {input} = variables

    const optimistic = {
        item: {
            ...input,
            __typename: 'Item'
        },
        __typename: 'updateItemPayload'
    };

    return optimistic;
}
```

The initial optimistic update correctly updates the Query data. The issue seems to arise after that, and manifests in a partial result, with only the optimistic Item being set, and all other `node` fields being set to null.

I don't really understand why that's the case, maybe I'm just using it incorrectly?

**Comment by kitten** [comment] 2019-09-13 17:49
Hiya 👋  just to make sure I'm getting this right:

- the query gives you a list of items
- you send the mutation
- the optimistic update correctly updates the query with the new name
- the result comes back and (?)

So I'm not quite clear on what happens once the actual mutation result comes back.
Are you saying that all other node fields are missing? Are you providing a schema to your graphcache exchange? Are you providing any resolvers? 🤔

**Comment by lukasluecke** [comment] 2019-09-13 17:54
After the result comes back the data I get in my component, using the list query with `useQuery`, all the previously set `node` fields in the `edges` are set to null (except the one with the optimistic update). So the edges stay there, but their nodes are missing, which is something that's not really expected with these Relay pagination queries (or at least I didn't experience that yet).

I am providing my schema (generated, so should be complete and correct), but no resolvers.

**Comment by kitten** [comment] 2019-09-13 17:57
Ok, I think I've found the bug. We've recently found some weird behaviour in `pessimism` with `clearOptimistic`, which is supposed to clear out all optimistic K/V entries.

I've just pushed a fix, so if you make sure to `yarn upgrade` to upgrade `pessimism` to `1.1.2` it should work correctly 🤞 

(For future reference, this is the fix: https://github.com/kitten/pessimism/commit/cd604473a8e1bdf1e9c1301961050c3ff95ad343)

**Comment by lukasluecke** [comment] 2019-09-13 18:13
Mh, still seem to be running into the same issue 🤔 I'll have to leave now, but will try to provide a compact reproduction later. Thank you for the quick replies! 🙂

**Comment by kitten** [comment] 2019-09-14 14:52
I think I may have a hunch on what may be going on. I think it may be related to writing nested embedded entities to the cache and reading them back. I'll have to write a test case for our suite to confirm, but I did notice that we're not testing for this case and it may very well be the culprit 😅

**Comment by lukasluecke** [comment] 2019-09-15 00:30
If you need anything else from me, just let me know 🙂 I'll work on the rest of my `updates` in the meantime, those work pretty nice already 👍

**Comment by kitten** [comment] 2019-09-15 23:56
I'm trying to hunt down this issue, and the piece of code where I suspected an issue is in fact correct as far as I've tested 🤔  I did however read through your sample again and there may be some things that aren't quite adding up. So I assume you're altering the queries and sample code and are slimming them down?

In your optimistic update you're spreading `variables` to the output, but that return value is then missing a `__typename`. That means that either the optimistic update can't be working in your example or there's another part of the mutation missing that may affect the Relay connection.

The reason why I think I'm missing information specifically is that this can only have a couple of causes, but they'd all need to affect at least the `edges` to be also affecting the `node` field.

**Comment by lukasluecke** [comment] 2019-09-15 23:59
Oh yeah I'm sorry, I have the `__typename` set (In my original example I did read a fragment from the store, and spread that first, so the typename was included there - but since that didn't really matter, I've removed it).

**Comment by lukasluecke** [comment] 2019-09-16 00:01
If you could tell me what exactly to look for, or how to test, I'd be happy to. I'm currently at the airport and will be offline for the next day or so, but I'll work on a runnable reproduction for you after that 🙂 

When I last tried it, the `edges` were all kept intact (as in the number of edges didn't change), but all of them except the one containing the just updated Item had their `node` set to null.

**Comment by kitten** [comment] 2019-09-16 00:18
I've pushed an initial reproduction to `temp/issue-80` that doesn't break (so working as expected), which is in the form of a Jest test that does the optimistic write. Right now, it's a copy of what you're describing but it seems that I'm missing a crucial detail here 🤔 https://github.com/FormidableLabs/urql-exchange-graphcache/commit/41aae38c36115fdaeade2403c0b139a935d21b6f#diff-d6d14b67a49036829ad311d8ce605a6bR354-R367

If you could take a look and point out what may be missing there, then that'd already be an immense help! 🙌

**Comment by lukasluecke** [comment] 2019-09-16 00:28
I‘ll check it in detail when I can, but just saw that the server write was commented out in your snippet, correct? My issue happens when the server write runs, not after the optimistic update itself.

**Comment by kitten** [comment] 2019-09-16 00:52
I did try it with the `write` that is commented out, but I forgot to add `store.clearOptimistic` and that does reproduce the bug successfully :tada: https://github.com/FormidableLabs/urql-exchange-graphcache/commit/494f9610f4a038718bd3df40a1df9c4f2aedbf33#diff-d6d14b67a49036829ad311d8ce605a6bR361

This is actually a good sign! Because it may mean that it's a small bug in the data structure again, that wasn't fixed as part of pessimism 1.1.2

**Comment by lukasluecke** [comment] 2019-09-16 01:05
Awesome, thanks for your work! 😊🎉

**Closed** 2019-09-16 01:48 UTC
Labels: bug 🐛

**Comment by kitten** [comment] 2019-09-16 01:52
Alright, I found the issue :tada: I thought I fixed it earlier in pessimism 1.1.2, but it turns out there was a more severe issue in how `clearOptimistic` was implemented before. However, we now have a solid test for this case and a new RC.9 release to force everyone onto pessimism 1.1.3 🎉

**Comment by lukasluecke** [comment] 2019-09-16 02:53
🎉 Damn, that was a quick fix! I‘ll be in the air for another 10 hours, but look forward to using this new version after that 😁

Glad I could help with a reproduction 😊 and once again, thanks for your work on this - urql has been a joy so far!

**Comment by lukasluecke** [comment] 2019-09-16 13:50
@kitten My example works now, so also a confirmed fix from my side 🙂
