### ISSUE TITLE
The optimistic updates are not cleared on errors

### ISSUE THREAD

**Issue by dragoscd** [FormidableLabs/urql-exchange-graphcache#159] opened 2020-01-29 10:10 UTC
If the server throws an unexpected error or the network connection goes down the optimistic data is not cleared.

**Comment by JoviDeCroock** [comment] 2020-01-29 10:22
Hey @dragoscd 

I've taken a quick look and it seems like this works in our tests, could you provide any more information. For instance do you have an exchange that re-throws this error?
If possible could you provide a minimal reproduction? This can speed up the finding of the bug in question

**Comment by dragoscd** [comment] 2020-01-29 12:36
I've used the `subscriptions` example and added a simple mutation there:

server:

```
Mutation: {
    addMessage: () => {
      throw new Error('Something');

      const newMessage = {
        id: ++id,
        message: StarWars.quote(),
        from: StarWars.character(),
      };
      store.messages.push(newMessage);

      return newMessage;
    },
  }, 
```

client:

```
const GetQuery = gql`
  query {
    messages {
      id
      message
    }
  }
`;

const client = createClient({
  url: 'http://localhost:4000/graphql',
  exchanges: [
    cacheExchange({
      updates: {
        Mutation: {
          addMessage: (data, _, cache) => {
            if (data && data.addMessage) {
              cache.updateQuery({ query: GetQuery }, (prevData: any) => {
               
                return {
                  ...prevData,
                  messages: [...(prevData.messages as Data[]), data.addMessage],
                };
              });
            }
          },
        },
      },
      optimistic: {
        addMessage: () => {
          return {
            id: 12312,
            message: 'This is the optimistic message,
            __typename: 'Message',
          };
        },
      },
    }),
    fetchExchange,
    subscriptionExchange({
      forwardSubscription: operation => subscriptionClient.request(operation),
    }),
  ],
});
```

**Comment by JoviDeCroock** [comment] 2020-01-29 12:54
Given that information the issue will be because this optimisticLayer is persisted by means of `cache.updateQuery` due to this line: https://github.com/FormidableLabs/urql-exchange-graphcache/blob/master/src/operations/write.ts#L165

**Comment by JoviDeCroock** [comment] 2020-01-31 11:19
Hey,

This is fixed by https://github.com/FormidableLabs/urql-exchange-graphcache/pull/160, if you run into any more issues with this feel free to reopen the issue!

**Closed by JoviDeCroock** 2020-01-31 11:19 UTC
Labels: bug 🐛

**Comment by dragoscd** [comment] 2020-01-31 12:04
Awesome, thanks for the quick support, I'll check it out
